import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="Budgeting app for gig workers"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="landingpage-pagewrapper">
        <section className="hook-section">
          <h1>Gig Budgeter</h1>
        </section>
        <section className="action-section"></section>
      </div>
    </div>
  );
};

export default Home;
